SELECT SQ1.ANIMAL_ID, SQ1.NAME
FROM (
    SELECT a.ANIMAL_ID, a.NAME, a.DATETIME AS ATIME, b.DATETIME AS BTIME
    FROM ANIMAL_INS a, ANIMAL_OUTS b
    WHERE a.ANIMAL_ID = b.ANIMAL_ID
    ) SQ1
WHERE SQ1.ATIME > SQ1.BTIME
ORDER BY SQ1.ATIME;
