
SELECT b.ANIMAL_ID, b.ANIMAL_TYPE, b.NAME
FROM (
    SELECT *
    FROM ANIMAL_INS a
    WHERE SEX_UPON_INTAKE LIKE '%Intact%'
    ) SQ1, ANIMAL_OUTS b
WHERE SQ1.ANIMAL_ID = b.ANIMAL_ID
AND b.SEX_UPON_OUTCOME NOT LIKE '%Intact%';
