
-- 0시부터 23시까지 시간대별로 입양 몇 건?
-- 시간대 순 정렬

WITH RECURSIVE CTE AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1 FROM CTE WHERE HOUR < 23
)
SELECT
    C.HOUR,
    COUNT(A.ANIMAL_ID) AS COUNT
FROM CTE AS C
    LEFT JOIN ANIMAL_OUTS AS A ON C.HOUR = HOUR(A.DATETIME)
GROUP BY
    HOUR
ORDER BY
    HOUR
