SELECT PRODUCT_CODE
, SUM(price*sales_amount) as SALES
from PRODUCT AS P
JOIN OFFLINE_SALE AS O ON P.PRODUCT_ID = O.PRODUCT_ID
GROUP BY PRODUCT_CODE
ORDER BY SUM(price*sales_amount) DESC, PRODUCT_CODE ASC
